### ISSUE TITLE
Export Error

### ISSUE THREAD

**Issue by SainteCelery** [mjswensen/themer-gui#18]
On macOS Mojave 10.14.2, while attempting to export a theme for Terminal, Atom Syntax & Atom UI, I am stymied by the error:

> themer-terminal: Error: /var/vf/......../.com/mjswensen.themer.PMPDEz:16:26: warning: 'archivedData(withRootObject:)' was deprecated in OS X 10.14: Use +archiveDataWithRootObject:requiringSecureCoding:error: instead return NSKeyedArchiver.archivedData( ^

**Comment by mjswensen** [comment]
@SainteCelery , what version of macOS are you using?

**Comment by mjswensen** [comment]
Hi @SainteCelery , This Electron-based app has been deprecated in favor of a Progressive Web App ([themer.mjswensen.com](https://themer.mjswensen.com)). Since `themer-terminal` runs a snippet of Swift code that needs access to Apple-proprietary APIs, `themer-terminal` can't be supported in the Web app and will therefore be CLI-only. Here are the [docs on how to use `themer-terminal` with `themer` CLI](https://github.com/mjswensen/themer/tree/master/cli/packages/themer-terminal).
